language: haskell
ghc: 7.6
sudo: false
cache:
  directories:
  - ~/.cabal
  - ~/.ghc

script:
  - cabal install happy alex Agda --constraint 'alex >= 3.1.0 && < 3.2' --constraint 'happy >=1.19.3 && <2' --constraint 'Agda == 2.4.0.*'
  - (mkdir -p ../stdlib; cd ../stdlib; curl -L https://github.com/agda/agda-stdlib/archive/v0.8.tar.gz|tar xz)

  - echo "AGDA_LIB=$(dirname $PWD)/stdlib/agda-stdlib-0.8/src" > agdaCheck.sh.conf
  - ./agdaCheck.sh
