# Based on http://docs.haskellstack.org/en/stable/travis_ci/ and
# http://docs.haskellstack.org/en/stable/GUIDE/#travis-with-caching
#
# Choose a lightweight base image; we provide our own build tools.
sudo: false
language: c
addons: {apt: {packages: [libgmp-dev]}}

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/build/inc-lc/ilc-agda/.stack-work

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal --install-ghc build Agda ilc
  - (mkdir -p ../stdlib; cd ../stdlib; curl -L https://github.com/agda/agda-stdlib/archive/v0.8.tar.gz|tar xz)

  - echo "AGDA_LIB=$(dirname $PWD)/stdlib/agda-stdlib-0.8/src" > agdaCheck.sh.conf
  - ./agdaCheck.sh
